25/02/2022 05:18:38-INFO-simpleSock.py-61 l2_socket established
25/02/2022 05:18:38-WARNING-simpleSock.py-89 True
25/02/2022 05:19:04-WARNING-simpleSock.py-107 60
25/02/2022 05:19:04-WARNING-simpleSock.py-108 ['', '01', '07', '08', '13', '19']
25/02/2022 05:19:04-WARNING-simpleSock.py-109 0:00:00.240444
25/02/2022 05:19:05-WARNING-simpleSock.py-107 60
25/02/2022 05:19:05-WARNING-simpleSock.py-108 ['', '01', '07', '13', '14', '20']
25/02/2022 05:19:05-WARNING-simpleSock.py-109 0:00:00.236387
25/02/2022 05:19:06-WARNING-simpleSock.py-107 69
25/02/2022 05:19:06-WARNING-simpleSock.py-108 ['', '01', '02', '07', '13', '18', '17', '23', '24']
25/02/2022 05:19:06-WARNING-simpleSock.py-109 0:00:00.236656
25/02/2022 05:19:06-WARNING-simpleSock.py-107 63
25/02/2022 05:19:06-WARNING-simpleSock.py-108 ['', '01', '07', '11', '17', '23', '19']
25/02/2022 05:19:06-WARNING-simpleSock.py-109 0:00:00.140936
25/02/2022 05:19:08-WARNING-simpleSock.py-107 66
25/02/2022 05:19:08-WARNING-simpleSock.py-108 ['', '01', '06', '11', '16', '22', '23', '24']
25/02/2022 05:19:08-WARNING-simpleSock.py-109 0:00:00.191302
25/02/2022 05:19:08-WARNING-simpleSock.py-107 63
25/02/2022 05:19:08-WARNING-simpleSock.py-108 ['', '01', '06', '12', '18', '24', '20']
25/02/2022 05:19:08-WARNING-simpleSock.py-109 0:00:00.224718
25/02/2022 05:19:10-WARNING-simpleSock.py-107 60
25/02/2022 05:19:10-WARNING-simpleSock.py-108 ['', '01', '02', '08', '14', '19']
25/02/2022 05:19:10-WARNING-simpleSock.py-109 0:00:00.140962
Traceback (most recent call last):
  File "/home/wifi/Downloads/simple/Idea-validation-ip-ccn/simpleSock.py", line 95, in <module>
    emptySocket(l2_sock)
  File "/home/wifi/Downloads/simple/Idea-validation-ip-ccn/simpleSock.py", line 21, in emptySocket
    _sck.recv(123)
OSError: [Errno 100] Network is down
